version: '3'

services:
  timetable:
    build: ./backend/client-services/timetable-service
    container_name: timetable-service
    restart: always
    environment:
      DATABASE_URI: postgresql://admin:admin@db:5432/unitrackdb
    ports:
      - "8000:8000"
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:8000/healthcheck"]
        interval: 20s
        timeout: 10s
        retries: 10
    depends_on:
      db:
        condition: service_healthy
    networks:
      - unitrack-network
  
  stop-timetable:
      build: ./backend/client-services/stop-timetable-service
      container_name: stop-timetable-service
      restart: always
      environment:
        DATABASE_URI: postgresql://admin:admin@db:5432/unitrackdb
      ports:
        - "8001:8000"
      healthcheck:
          test: ["CMD", "curl", "-f", "http://localhost:8000/healthcheck"]
          interval: 20s
          timeout: 10s
          retries: 10
      depends_on:
        db:
          condition: service_healthy
      networks:
      - unitrack-network

  stop:
    build: ./backend/client-services/stop-service
    container_name: stop-service
    restart: always
    environment:
      DATABASE_URI: postgresql://admin:admin@db:5432/unitrackdb
    ports:
      - "8002:8000"
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:8000/healthcheck"]
        interval: 20s
        timeout: 10s
        retries: 10
    depends_on:
      db:
        condition: service_healthy
    networks:
      - unitrack-network

  login:
    build: ./backend/auth-services/login-service
    container_name: login-service
    restart: always
    environment:
      DATABASE_URI: postgresql://admin:admin@db:5432/unitrackdb
      JWT_SECRET_KEY: 8GvBesJUFFHE5FHTGnD8LjfWI9BK4A3l

    ports:
      - "8003:8000"
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:8000/healthcheck"]
        interval: 20s
        timeout: 10s
        retries: 10
    depends_on:
      db:
        condition: service_healthy
    networks:
      - unitrack-network

  refresh-token:
    build: ./backend/auth-services/refresh-token-service
    container_name: refresh-token-service
    restart: always
    environment:
      DATABASE_URI: postgresql://admin:admin@db:5432/unitrackdb
      JWT_SECRET_KEY: 8GvBesJUFFHE5FHTGnD8LjfWI9BK4A3l

    ports:
      - "8004:8000"
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:8000/healthcheck"]
        interval: 20s
        timeout: 10s
        retries: 10
    depends_on:
      db:
        condition: service_healthy
    networks:
      - unitrack-network

  user-create:
    build: ./backend/admin-services/user-services/user-create-service
    container_name: user-create-service
    restart: always
    environment:
      DATABASE_URI: postgresql://admin:admin@db:5432/unitrackdb
      JWT_SECRET_KEY: 8GvBesJUFFHE5FHTGnD8LjfWI9BK4A3l
    ports:
      - "8005:8000"
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:8000/healthcheck"]
        interval: 20s
        timeout: 10s
        retries: 10
    depends_on:
      db:
        condition: service_healthy
    networks:
      - unitrack-network

  user-read:
    build: ./backend/admin-services/user-services/user-read-service
    container_name: user-read-service
    restart: always
    environment:
      DATABASE_URI: postgresql://admin:admin@db:5432/unitrackdb
      JWT_SECRET_KEY: 8GvBesJUFFHE5FHTGnD8LjfWI9BK4A3l
    ports:
      - "8006:8000"
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:8000/healthcheck"]
        interval: 20s
        timeout: 10s
        retries: 10
    depends_on:
      db:
        condition: service_healthy
    networks:
      - unitrack-network

  user-update:
    build: ./backend/admin-services/user-services/user-update-service
    container_name: user-update-service
    restart: always
    environment:
      DATABASE_URI: postgresql://admin:admin@db:5432/unitrackdb
      JWT_SECRET_KEY: 8GvBesJUFFHE5FHTGnD8LjfWI9BK4A3l
    ports:
      - "8007:8000"
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:8000/healthcheck"]
        interval: 20s
        timeout: 10s
        retries: 10
    depends_on:
      db:
        condition: service_healthy
    networks:
      - unitrack-network

  user-delete:
    build: ./backend/admin-services/user-services/user-delete-service
    container_name: user-delete-service
    restart: always
    environment:
      DATABASE_URI: postgresql://admin:admin@db:5432/unitrackdb
      JWT_SECRET_KEY: 8GvBesJUFFHE5FHTGnD8LjfWI9BK4A3l
    ports:
      - "8008:8000"
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:8000/healthcheck"]
        interval: 20s
        timeout: 10s
        retries: 10
    depends_on:
      db:
        condition: service_healthy
    networks:
      - unitrack-network

  timetable-create:
    build: ./backend/timetable-services/timetable-create-service
    container_name: timetable-create-service
    restart: always
    environment:
      DATABASE_URI: postgresql://admin:admin@db:5432/unitrackdb
      JWT_SECRET_KEY: 8GvBesJUFFHE5FHTGnD8LjfWI9BK4A3l
    ports:
      - "8009:8000"
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:8000/healthcheck"]
        interval: 20s
        timeout: 10s
        retries: 10
    depends_on:
      db:
        condition: service_healthy
    networks:
      - unitrack-network

  timetable-update:
    build: ./backend/timetable-services/timetable-update-service
    container_name: timetable-update-service
    restart: always
    environment:
      DATABASE_URI: postgresql://admin:admin@db:5432/unitrackdb
      JWT_SECRET_KEY: 8GvBesJUFFHE5FHTGnD8LjfWI9BK4A3l
    ports:
      - "8010:8000"
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:8000/healthcheck"]
        interval: 20s
        timeout: 10s
        retries: 10
    depends_on:
      db:
        condition: service_healthy
    networks:
      - unitrack-network

  timetable-delete:
    build: ./backend/timetable-services/timetable-delete-service
    container_name: timetable-delete-service
    restart: always
    environment:
      DATABASE_URI: postgresql://admin:admin@db:5432/unitrackdb
      JWT_SECRET_KEY: 8GvBesJUFFHE5FHTGnD8LjfWI9BK4A3l
    ports:
      - "8011:8000"
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:8000/healthcheck"]
        interval: 20s
        timeout: 10s
        retries: 10
    depends_on:
      db:
        condition: service_healthy
    networks:
      - unitrack-network

  stop-create:
    build: ./backend/stop-services/stop-create-service
    container_name: stop-create-service
    restart: always
    environment:
      DATABASE_URI: postgresql://admin:admin@db:5432/unitrackdb
      JWT_SECRET_KEY: 8GvBesJUFFHE5FHTGnD8LjfWI9BK4A3l
    ports:
      - "8012:8000"
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:8000/healthcheck"]
        interval: 20s
        timeout: 10s
        retries: 10
    depends_on:
      db:
        condition: service_healthy
    networks:
      - unitrack-network

  stop-read:
    build: ./backend/stop-services/stop-read-service
    container_name: stop-read-service
    restart: always
    environment:
      DATABASE_URI: postgresql://admin:admin@db:5432/unitrackdb
      JWT_SECRET_KEY: 8GvBesJUFFHE5FHTGnD8LjfWI9BK4A3l
    ports:
      - "8013:8000"
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:8000/healthcheck"]
        interval: 20s
        timeout: 10s
        retries: 10
    depends_on:
      db:
        condition: service_healthy
    networks:
      - unitrack-network

  stop-update:
    build: ./backend/stop-services/stop-update-service
    container_name: stop-update-service
    restart: always
    environment:
      DATABASE_URI: postgresql://admin:admin@db:5432/unitrackdb
      JWT_SECRET_KEY: 8GvBesJUFFHE5FHTGnD8LjfWI9BK4A3l
    ports:
      - "8014:8000"
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:8000/healthcheck"]
        interval: 20s
        timeout: 10s
        retries: 10
    depends_on:
      db:
        condition: service_healthy
    networks:
      - unitrack-network

  stop-delete:
    build: ./backend/stop-services/stop-delete-service
    container_name: stop-delete-service
    restart: always
    environment:
      DATABASE_URI: postgresql://admin:admin@db:5432/unitrackdb
      JWT_SECRET_KEY: 8GvBesJUFFHE5FHTGnD8LjfWI9BK4A3l
    ports:
      - "8015:8000"
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:8000/healthcheck"]
        interval: 20s
        timeout: 10s
        retries: 10
    depends_on:
      db:
        condition: service_healthy
    networks:
      - unitrack-network

  web:
    build: ./frontend/web
    container_name: web-app
    restart: always
    environment:
      VITE_API_STOP_URL: http://stop:8000
      VITE_API_TIMETABLE_URL: http://timetable-service:8000
      VITE_API_STOP_TIMETABLE_URL: http://stop-timetable:8000
    ports:
      - "80:80"
    depends_on:
        stop:
            condition: service_healthy
        timetable:
            condition: service_healthy
        stop-timetable:
            condition: service_healthy
    networks:
      - unitrack-network

  db:
    image: postgres:latest
    restart: always
    container_name: unitrack-db
    hostname: myhost
    environment:
      POSTGRES_DB: unitrackdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - ./backend/db/volumes:/var/lib/postgresql/data
      - ./backend/db/CREATE_DB.sql:/docker-entrypoint-initdb.d/CREATE_DB.sql
      - ./backend/db/INSERT_DB.sql:/docker-entrypoint-initdb.d/INSERT_DB.sql
    ports:
      - "9091:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "admin", "-d", "unitrackdb", "-h", "localhost", "-p", "5432"]
      interval: 20s
      timeout: 10s
      retries: 10
    networks:
      - unitrack-network

networks:
  unitrack-network: