-- Llenado Base de datos

INSERT INTO stop (name, description, latitude, longitude, image) VALUES    ('Afueras bloque apartamentos','En la esquina a la entrada de la Madrid etapa 3',4.0593938,-73.6700653, 'https://res.cloudinary.com/dynfsoflz/image/upload/v1676308878/Porfia/pPorf1_pul4kf.png'),
                                                                        ('Supermercado Marketing','Supermercado Marketing',4.064833,-73.671318, 'https://res.cloudinary.com/dynfsoflz/image/upload/v1676308882/Porfia/pPorf2_xervoe.png'),
                                                                        ('Salida los Chopos','Frente a la ferretería Las Palmas, diagonal a los Chopos',4.073257, -73.669342, 'https://res.cloudinary.com/dynfsoflz/image/upload/v1676308880/Porfia/pPorf3_xx0la2.png'),
                                                                        ('Congente','Frente a cajero congente',4.079063, -73.669262, 'https://res.cloudinary.com/dynfsoflz/image/upload/v1676308881/Porfia/pPorf4_s10ixk.png'),
                                                                        ('Consuerte','Diagonal templo católico semáforo Consuerte',4.0826917,-73.6692422, 'https://res.cloudinary.com/dynfsoflz/image/upload/v1676308879/Porfia/pPorf5_zrhmea.png'),
                                                                        ('Bomba Texaco','Esquina de la bomba de gasolina en la entrada a porfia',4.088458, -73.670179, 'https://res.cloudinary.com/dynfsoflz/image/upload/v1676308876/Porfia/pPorf6_ebhx0u.png'),
                                                                        (' Segunda entrada Samán','Segunda entrada Samán en el puente peatonal', 4.091312, -73.666702, 'https://res.cloudinary.com/dynfsoflz/image/upload/v1676308876/Porfia/pPorf7_gvmo11.png'),
--Viva                                  
                                                                        ('Esquina semáforo de Viva','Frente al conjunto, donde está el semaforo',4.125370, -73.636071, 'https://res.cloudinary.com/dynfsoflz/image/upload/v1676308876/Viva/pViva1_pt9boe.png'),
                                                                        ('Boutique Revival','Frente a la Boutique',4.124263, -73.634550, 'https://res.cloudinary.com/dynfsoflz/image/upload/v1676308873/Viva/pViva2_gwqmoe.png'),
                                                                        ('Casa Jeréz Inmobiliaria','En la esquina despues del parque donde está la cancha',4.123136,-73.6321427, 'https://res.cloudinary.com/dynfsoflz/image/upload/v1676308879/Viva/pViva3_oqirdk.png'),
                                                                        ('Calle 33-45 esquina','En la papelería al lado de una tienda esquinera',4.1228957,-73.6296829, 'https://res.cloudinary.com/dynfsoflz/image/upload/v1676308874/Viva/pViva4_xacdc2.png'),
                                                                        ('Panadería y pastelería La Cosmopolita','Panadería esquinera',4.1191422,-73.6284305, 'https://res.cloudinary.com/dynfsoflz/image/upload/v1676308873/Viva/pViva5_kiqb0t.png'),
                                                                        ('Carrera 28F esquina','Casa esquinera con un poste de luz',4.1198703,-73.6257133, 'https://res.cloudinary.com/dynfsoflz/image/upload/v1676308873/Viva/pViva6_ijhesd.png'),
--Villacentro
                                                                        ('Frente Llanocentro','Debajo del puente peatonal frente a llanocentro al lado de Movistar',4.1331923,-73.6366531, 'https://res.cloudinary.com/dynfsoflz/image/upload/v1676308879/Villacentro/pVilc1_krje6n.png'),
                                                                        ('Comidas rapidas mazorcas','Frente al negocio Kikolo Mazorcas',4.1333947,-73.6353101, 'https://res.cloudinary.com/dynfsoflz/image/upload/v1676308872/Villacentro/pVilc2_opzt18.png'),
                                                                        ('Paradero busetas Dóminos','Paredero al lado del parqueadero antes del nuevo semaforo',4.1324333,-73.6324242, 'https://res.cloudinary.com/dynfsoflz/image/upload/v1676308874/Villacentro/pVilc3_eue5uf.png'),
                                                                        ('Droguería la rebaja','Droguería antes de llegar a Sipote',4.1314713,-73.6295618, 'https://res.cloudinary.com/dynfsoflz/image/upload/v1676308879/Villacentro/pVilc4_h8xebo.png'),
--Grama-Postobon
                                                                        ('Cuatro Parques','En el paradero de busetas que tiene el parque',4.158367, -73.640998, 'https://res.cloudinary.com/dynfsoflz/image/upload/v1676308881/Grama-Postobon/pGrPb1_vbf5il.png'),
                                                                        ('Picadas y algo más','En la esquina donde está el restaurante',4.157906, -73.637702, 'https://res.cloudinary.com/dynfsoflz/image/upload/v1676308880/Grama-Postobon/pGrPb2_tqqpxf.png'),
                                                                        ('Frente Bomba Texaco','Frente Bomba Texaco',4.156651, -73.632235, 'https://res.cloudinary.com/dynfsoflz/image/upload/v1676308873/Grama-Postobon/pGrPb3_iyxw5k.png'),
                                                                        ('Droguería la Providencia','En la esquina de la droguería',4.151178, -73.628527, 'https://res.cloudinary.com/dynfsoflz/image/upload/v1676308874/Grama-Postobon/pGrPb4_ohdrif.png'),
                                                                        ('Yamaha Jordán','Antes de llegar al semaforo en el motomusic',4.148175, -73.624406, 'https://res.cloudinary.com/dynfsoflz/image/upload/v1676308878/Grama-Postobon/pGrPb5_llvwl7.png'),
                                                                        ('Paradero busetas COFREM','Donde paran la busetas',4.147615, -73.620722, 'https://res.cloudinary.com/dynfsoflz/image/upload/v1676308881/Grama-Postobon/pGrPb6_wjbyxj.png'),
                                                                        ('Fresilandia','Unas casas antes de Fresilandia, donde está un arbol con una silla',4.1416635,-73.6210014, 'https://res.cloudinary.com/dynfsoflz/image/upload/v1676308880/Grama-Postobon/pGrPb7_fuahac.png'),
                                                                        ('Esquina parque SIKUANI','Abajo del puente peatonal frente SIKUANI',4.1369872,-73.6218195, 'https://res.cloudinary.com/dynfsoflz/image/upload/v1676308881/Grama-Postobon/pGrPb8_sbkwfn.png'),
                                                                        ('Paradero busetas Cantarrana','Donde paran la busetas',4.1345282,-73.6230187, 'https://res.cloudinary.com/dynfsoflz/image/upload/v1676308881/Grama-Postobon/pGrPb9_enrtpm.png'),
--Terminal
                                                                        ('Yamaha Jordán','Antes de llegar al semaforo en el motomusic',4.148175, -73.624406, 'https://res.cloudinary.com/dynfsoflz/image/upload/v1676308876/Terminal/pTerm1_bv0mf6.png'),
                                                                        ('Paradero busetas COFREM','Donde paran la busetas',4.147615, -73.620722, 'https://res.cloudinary.com/dynfsoflz/image/upload/v1676308877/Terminal/pTerm2_giwwza.png'),
                                                                        ('Paradero buses Hato Grande','Diagonal a Hato Grande',4.1470082,-73.6168287, 'https://res.cloudinary.com/dynfsoflz/image/upload/v1676308877/Terminal/pTerm3_adxjea.png'),
                                                                        ('Frente a Olimpica','Puesto de salud que está frente a Olimpica',4.1461767,-73.6112503, 'https://res.cloudinary.com/dynfsoflz/image/upload/v1676308872/Terminal/pTerm4_pxgh6a.png'),
                                                                        ('Semaforo Manantial','Semaforo frente al CDA',4.1453019,-73.6066442, 'https://res.cloudinary.com/dynfsoflz/image/upload/v1676308875/Terminal/pTerm5_xq0sf3.png'),
                                                                        ('Semaforo entrada Morgue','Semaforo que queda antes de voltear a la derecha para la morgue',4.1388252,-73.6029798, 'https://res.cloudinary.com/dynfsoflz/image/upload/v1676308875/Terminal/pTerm6_i9dcym.png'),
                                                                        ('La Cummins','Negocio llamado La Cummins al lado de los lugares donde se le echa aire a los carros',4.1352913,-73.6042122, 'https://res.cloudinary.com/dynfsoflz/image/upload/v1676308873/Terminal/pTerm7_gjiduk.png'),
                                                                        ('Colanta','Colanta ubicada antes de la bomba terpel y diagonal a la bomba del terminal',4.1306709,-73.6058219, 'https://res.cloudinary.com/dynfsoflz/image/upload/v1676308875/Terminal/pTerm8_npeq1e.png'),
                                                                        ('Llanabastos','Semaforo cuadra antes de llanabastos, donde se voltea para entrar a los barrios',4.1254451,-73.6098398, 'https://res.cloudinary.com/dynfsoflz/image/upload/v1676308877/Terminal/pTerm9_ewcqua.png'),
--Covisan
                                                                        ('Semaforo pinilla','Primer semaforo bajando del CAI de la policía o semaforo para entrar al Pinilla',4.1375399,-73.5892802, 'https://res.cloudinary.com/dynfsoflz/image/upload/v1676308878/Covisan/pCovs1_lvdmyz.png'),
                                                                        ('Bomba Terpel Covisan','Frente a la bomba terpel por donde bajan los carros',4.1371736,-73.5863872, 'https://res.cloudinary.com/dynfsoflz/image/upload/v1676308878/Covisan/pCovs2_hmfq77.png'),
                                                                        ('El Salitre','Entrada al barrio Ciudad Salitre',4.1375301,-73.5808545, 'https://res.cloudinary.com/dynfsoflz/image/upload/v1676308873/Covisan/pCovs3_gsuiei.png'),
                                                                        ('Apartamentos Amarilo','En la entrada a los apartamentos Amarilo - Catama',4.1358266,-73.5731425, 'https://res.cloudinary.com/dynfsoflz/image/upload/v1676308874/Covisan/pCovs4_xf36jw.png'),
                                                                        ('El campanario','Esquina volteando a la derecha del Campanario',4.1332609,-73.5653911, 'https://res.cloudinary.com/dynfsoflz/image/upload/v1676308873/Covisan/pCovs5_r4fyip.png'),
                                                                        ('Entrada San Antonio','Esquina entrada al barrio San Antonio',4.1281839,-73.569041, 'https://res.cloudinary.com/dynfsoflz/image/upload/v1676308875/Covisan/pCovs6_ewld3o.png'),
                                                                        ('Kirpan','Frente a la panadería llamada Kirpan en Kirpas',4.1179943,-73.5854076, 'https://res.cloudinary.com/dynfsoflz/image/upload/v1676308874/Covisan/pCovs7_v4pqfl.png'),
                                                                        ('PanRolo','Barrio Villamelida, frente a la panadería Pan Rolo',4.1163216,-73.5972501, 'https://res.cloudinary.com/dynfsoflz/image/upload/v1676308875/Covisan/pCovs8_obdgcq.png'),
-- Maracos
                                                                        ('Bomba los Maracos','En la bomba Texaco al lado de la cancha sintetica',4.135574,-73.6181454, 'https://res.cloudinary.com/dynfsoflz/image/upload/v1676308874/Maracos/pMarc1_fmqaeu.png'),
                                                                        ('Semaforo lavadero','En el semaforo al frente del lavadero esquinero',4.1340915,-73.6132462, 'https://res.cloudinary.com/dynfsoflz/image/upload/v1676308882/Maracos/pMarc2_ssoiwp.png'),
                                                                        ('Parque Mi Llanura','En el semaforo del parque mi llanura, donde hay una señal de policía acostado',4.1326294,-73.608517, 'https://res.cloudinary.com/dynfsoflz/image/upload/v1676308882/Maracos/pMarc3_qpikg8.png'),
                                                                        ('Glorieta Terminal','Justo terminando la glorieta para seguir bajando por la avenida',4.1303038,-73.601359, 'https://res.cloudinary.com/dynfsoflz/image/upload/v1676308879/Maracos/pMarc4_fppizm.png'),
                                                                        ('Semaforo Pinilla Alto','Esquina del Pinilla, ruta de la busetas, conexión con Covisan',4.1296156,-73.5894141, 'https://res.cloudinary.com/dynfsoflz/image/upload/v1676308882/Maracos/pMarc5_afs4z2.png'),
                                                                        ('Kirpan','Frente a la panadería llamada Kirpan en Kirpas',4.1179943,-73.5854076, 'https://res.cloudinary.com/dynfsoflz/image/upload/v1676308874/Maracos/pMarc6_eullui.png'),
                                                                        ('PanRolo','Barrio Villamelida, frente a la panadería Pan Rolo',4.1163216,-73.5972501, 'https://res.cloudinary.com/dynfsoflz/image/upload/v1676308879/Maracos/pMarc7_h83dpp.png'),
-- Montecarlo
                                                                        ('La Rochela','Salida del barrio La Rochela a la avenida',4.1044181,-73.6568555, 'https://res.cloudinary.com/dynfsoflz/image/upload/v1676308879/Montecarlo/pMont1_cffwil.png'),
                                                                        ('Bomba Terpel Playa Rica','Frente a la bomba Terpel',4.1072854,-73.6557697, 'https://res.cloudinary.com/dynfsoflz/image/upload/v1676308877/Montecarlo/pMont2_kylspl.png'),
                                                                        ('Bahía Serramonte','Frente a la bomba Primax de Serramonte',4.1155424,-73.6490235, 'https://res.cloudinary.com/dynfsoflz/image/upload/v1676308875/Montecarlo/pMont3_tovbg8.png'),
                                                                        ('Amarilo','En la esquina del conjunto cimarron',4.1097822,-73.6329908, 'https://res.cloudinary.com/dynfsoflz/image/upload/v1676308875/Montecarlo/pMont4_nnvhpd.png'),
-- Parque                                                                        
                                                                        ('Parque de los estudiante','Diagonal al parque de los estudiante, al lado del Justo y Bueno',4.1459132,-73.6366358, 'https://res.cloudinary.com/dynfsoflz/image/upload/v1676308878/Parque/pParq1_ymoesl.png'),
                                                                        ('Unicentro','Paradero de busetas Unicentro - Vía Pto. Lopez',4.1432595,-73.6334785, 'https://res.cloudinary.com/dynfsoflz/image/upload/v1676308882/Parque/pParq2_fbg2ny.png'),
                                                                        ('Tecniguayas','Diagonal al colegio Normal, esquina donde está el local Tecniguayas',4.138734,-73.6300699, 'https://res.cloudinary.com/dynfsoflz/image/upload/v1676308880/Parque/pParq3_caor4i.png'),
                                                                        ('La Industrial','Acera en frente del Colegio Industrial, en señalización junto al poste',4.1352434,-73.6273911, 'https://res.cloudinary.com/dynfsoflz/image/upload/v1676308878/Parque/pParq4_rufqau.png'),
                                                                        ('Makro','Paradero de busetas en Makro',4.1284916,-73.6222394, 'https://res.cloudinary.com/dynfsoflz/image/upload/v1676308882/Parque/pParq5_rspjes.png'),
                                                                        ('Alborada','Paradero de busetas al lado de Max-Autos',4.1246844,-73.619346, 'https://res.cloudinary.com/dynfsoflz/image/upload/v1676308880/Parque/pParq6_lbzyip.png'),
                                                                        ('Cooperativa','Bajo el puente peatonal de la cooperativa',4.1156645,-73.6095403, 'https://res.cloudinary.com/dynfsoflz/image/upload/v1676308880/Parque/pParq7_ppw9vs.png'),
                                                                        ('Bomba Primax','Luego de pasar el Ocoa, en la mitad de la bomba para',4.1108026,-73.6035419, 'https://res.cloudinary.com/dynfsoflz/image/upload/v1676308877/Parque/pParq8_hlaxux.png');



INSERT INTO timetable (hour) VALUES ('5:00:00'),
                                    ('6:00:00'),
                                    ('7:00:00'),
                                    ('8:00:00'),
                                    ('9:00:00'),
                                    ('10:00:00'),
                                    ('11:00:00'),
                                    ('12:00:00'),
                                    ('13:00:00'),
                                    ('14:00:00'),
                                    ('15:00:00'),
                                    ('16:00:00');

INSERT INTO stop_timetable (stop_id, timetable_id) VALUES (1,1),
                                                          (1,3),
                                                          (1,5),
                                                          (1,7),
                                                          (1,9),
                                                          (1,11),
                                                          (2,2),
                                                          (2,4),
                                                          (2,6),
                                                          (2,8),
                                                          (2,10),
                                                          (3,1),
                                                          (3,2),
                                                          (3,3),
                                                          (3,4),
                                                          (3,5),
                                                          (3,6),
                                                          (3,7),
                                                          (4,8),
                                                          (4,9),
                                                          (4,10),
                                                          (4,11),
                                                          (4,12),
                                                          (5,12),
                                                          (5,10),
                                                          (5,8),
                                                          (5,6),
                                                          (5,4),
                                                          (5,2),
                                                          (6,11),
                                                          (6,9),
                                                          (6,7),
                                                          (6,5),
                                                          (6,3),
                                                          (6,1),
                                                          (7,10),
                                                          (7,9),
                                                          (7,8),
                                                          (7,6),
                                                          (7,4),
                                                          (7,2),
                                                          (8,1),
                                                          (8,3),
                                                          (8,5),
                                                          (8,7),
                                                          (8,9),
                                                          (8,11),
                                                          (8,2),
                                                          (8,4),
                                                          (8,6),
                                                          (9,8),
                                                          (9,10),
                                                          (9,1),
                                                          (9,2),
                                                          (9,3),
                                                          (9,4),
                                                          (9,5),
                                                          (9,6),
                                                          (10,7),
                                                          (10,8),
                                                          (10,9),
                                                          (10,6),
                                                          (10,11),
                                                          (10,12),
                                                          (10,1),
                                                          (10,4),
                                                          (11,8),
                                                          (11,6),
                                                          (11,4),
                                                          (11,2),
                                                          (11,11),
                                                          (11,9),
                                                          (11,7),
                                                          (12,5),
                                                          (12,3),
                                                          (12,1),
                                                          (12,10),
                                                          (12,9),
                                                          (12,8),
                                                          (13,6),
                                                          (13,4),
                                                          (13,2),
                                                          (13,5),
                                                          (13,3),
                                                          (13,1),
                                                          (13,10),
                                                          (14,1),
                                                          (14,3),
                                                          (14,5),
                                                          (14,7),
                                                          (14,9),
                                                          (15,11),
                                                          (15,2),
                                                          (15,4),
                                                          (15,6),
                                                          (15,8),
                                                          (15,10),
                                                          (15,1),
                                                          (16,2),
                                                          (16,3),
                                                          (16,4),
                                                          (16,5),
                                                          (16,6),
                                                          (16,7),
                                                          (16,8),
                                                          (17,9),
                                                          (17,10),
                                                          (17,11),
                                                          (17,12),
                                                          (18,12),
                                                          (18,10),
                                                          (18,8),
                                                          (18,6),
                                                          (18,4),
                                                          (18,2),
                                                          (18,11),
                                                          (18,9),
                                                          (19,7),
                                                          (19,5),
                                                          (19,3),
                                                          (19,1),
                                                          (19,10),
                                                          (19,9),
                                                          (19,8),
                                                          (20,6),
                                                          (20,4),
                                                          (20,2),
                                                          (20,1),
                                                          (20,3),
                                                          (20,5),
                                                          (20,7),
                                                          (20,9),
                                                          (21,11),
                                                          (21,2),
                                                          (21,4),
                                                          (21,6),
                                                          (21,8),
                                                          (21,10),
                                                          (21,1),
                                                          (21,12),
                                                          (22,3),
                                                          (22,4),
                                                          (22,5),
                                                          (22,6),
                                                          (23,7),
                                                          (23,8),
                                                          (23,9),
                                                          (23,10),
                                                          (23,11),
                                                          (23,12),
                                                          (23,1),
                                                          (24,10),
                                                          (24,8),
                                                          (24,6),
                                                          (24,4),
                                                          (24,2),
                                                          (24,11),
                                                          (24,9),
                                                          (24,7),
                                                          (24,5),
                                                          (24,3),
                                                          (25,1),
                                                          (25,10),
                                                          (25,9),
                                                          (25,8),
                                                          (25,6),
                                                          (25,4),
                                                          (25,2),
                                                          (25,5),
                                                          (26,3),
                                                          (26,1),
                                                          (26,10),
                                                          (26,4),
                                                          (26,9),
                                                          (26,8),
                                                          (26,6),
                                                          (26,5),
                                                          (26,2),
                                                          (27,1),
                                                          (27,7),
                                                          (27,5),
                                                          (27,8),
                                                          (27,9),
                                                          (27,11),
                                                          (27,2),
                                                          (27,4),
                                                          (28,6),
                                                          (28,8),
                                                          (28,10),
                                                          (28,1),
                                                          (28,2),
                                                          (28,3),
                                                          (28,4),
                                                          (29,5),
                                                          (29,6),
                                                          (29,7),
                                                          (29,8),
                                                          (29,9),
                                                          (29,10),
                                                          (29,11),
                                                          (29,12),
                                                          (30,12),
                                                          (30,10),
                                                          (30,8),
                                                          (30,6),
                                                          (30,4),
                                                          (30,2),
                                                          (30,11),
                                                          (30,9),
                                                          (30,7),
                                                          (31,5),
                                                          (31,3),
                                                          (31,1),
                                                          (31,10),
                                                          (31,9),
                                                          (31,8),
                                                          (32,6),
                                                          (32,4),
                                                          (32,2),
                                                          (32,1),
                                                          (32,3),
                                                          (32,5),
                                                          (32,7),
                                                          (32,9),
                                                          (33,11),
                                                          (33,2),
                                                          (33,4),
                                                          (33,6),
                                                          (33,8),
                                                          (33,10),
                                                          (33,1),
                                                          (34,2),
                                                          (34,3),
                                                          (34,4),
                                                          (34,5),
                                                          (34,6),
                                                          (35,7),
                                                          (35,8),
                                                          (35,9),
                                                          (35,10),
                                                          (35,11),
                                                          (35,12),
                                                          (35,1),
                                                          (36,10),
                                                          (36,8),
                                                          (36,6),
                                                          (36,4),
                                                          (36,2),
                                                          (36,11),
                                                          (37,9),
                                                          (37,7),
                                                          (37,5),
                                                          (37,3),
                                                          (37,1),
                                                          (37,10),
                                                          (38,9),
                                                          (38,8),
                                                          (38,6),
                                                          (38,4),
                                                          (38,2),
                                                          (38,5),
                                                          (39,3),
                                                          (39,1),
                                                          (39,10),
                                                          (39,11),
                                                          (40,3),
                                                          (40,5),
                                                          (40,7),
                                                          (40,9),
                                                          (40,11),
                                                          (40,2),
                                                          (41,4),
                                                          (41,6),
                                                          (41,8),
                                                          (41,10),
                                                          (41,1),
                                                          (41,2),
                                                          (41,3),
                                                          (42,4),
                                                          (42,5),
                                                          (42,6),
                                                          (42,7),
                                                          (42,8),
                                                          (42,9),
                                                          (42,10),
                                                          (43,11),
                                                          (43,12),
                                                          (43,1),
                                                          (43,10),
                                                          (43,8),
                                                          (43,6),
                                                          (44,4),
                                                          (44,2),
                                                          (44,11),
                                                          (44,9),
                                                          (44,7),
                                                          (44,5),
                                                          (44,3),
                                                          (45,1),
                                                          (45,10),
                                                          (45,9),
                                                          (45,8),
                                                          (45,6),
                                                          (45,4),
                                                          (46,2),
                                                          (46,1),
                                                          (46,3),
                                                          (46,5),
                                                          (46,7),
                                                          (46,9),
                                                          (46,11),
                                                          (47,2),
                                                          (47,4),
                                                          (47,6),
                                                          (47,8),
                                                          (47,10),
                                                          (47,1),
                                                          (48,2),
                                                          (48,3),
                                                          (48,4),
                                                          (48,5),
                                                          (48,6),
                                                          (48,7),
                                                          (49,8),
                                                          (49,9),
                                                          (49,10),
                                                          (49,11),
                                                          (49,12),
                                                          (49,1),
                                                          (49,2),
                                                          (50,8),
                                                          (50,6),
                                                          (50,4),
                                                          (50,2),
                                                          (50,11),
                                                          (50,9),
                                                          (50,7),
                                                          (51,5),
                                                          (51,3),
                                                          (51,1),
                                                          (51,10),
                                                          (51,9),
                                                          (51,8),
                                                          (52,6),
                                                          (52,4),
                                                          (52,2),
                                                          (52,5),
                                                          (52,3),
                                                          (52,1),
                                                          (52,10),
                                                          (54,10),
                                                          (54,9),
                                                          (54,8),
                                                          (54,6),
                                                          (54,4),
                                                          (54,2),
                                                          (55,6),
                                                          (55,4),
                                                          (55,2),
                                                          (55,5),
                                                          (55,3),
                                                          (55,1),
                                                          (56,10),
                                                          (56,1),
                                                          (56,3),
                                                          (56,5),
                                                          (56,7),
                                                          (56,9),
                                                          (56,11),
                                                          (57,2),
                                                          (57,4),
                                                          (57,6),
                                                          (57,8),
                                                          (57,10),
                                                          (57,1),
                                                          (58,2),
                                                          (58,3),
                                                          (58,4),
                                                          (58,5),
                                                          (58,6),
                                                          (58,7),
                                                          (58,8),
                                                          (59,9),
                                                          (59,10),
                                                          (59,11),
                                                          (59,12),
                                                          (59,3),
                                                          (60,10),
                                                          (60,8),
                                                          (60,6),
                                                          (60,4),
                                                          (60,2),
                                                          (60,11),
                                                          (60,9),
                                                          (61,7),
                                                          (61,5),
                                                          (61,3),
                                                          (61,1),
                                                          (61,10),
                                                          (61,9),
                                                          (62,8),
                                                          (62,6),
                                                          (62,4),
                                                          (62,2),
                                                          (62,1),
                                                          (62,3),
                                                          (62,5),
                                                          (62,7),
                                                          (62,9);
                                                        